// src/components/base/Tooltip.tsx
import clsx from 'clsx';
import type { ReactNode } from 'react';

import { ariaBool } from '$utils/aria';

export type TooltipProps = {
	id: string;
	className?: string;
	visible?: boolean;
	children: ReactNode;
};

function Tooltip({ id, className, visible = false, children }: TooltipProps) {
	return (
		<div
			id={id}
			className={clsx(
				'transition-opacity absolute bottom-0 right-0 top-full mt-1 z-50',
				!visible && 'opacity-0 invisible',
				className,
			)}
			role="tooltip"
			aria-hidden={ariaBool(!visible)}
		>
			<span className="py-1.5 px-2 shadow-card flex items-center justify-center text-sm tracking-wider font-medium rounded-sm bg-surface dark:border-2 border-highlight">
				{children}
			</span>
		</div>
	);
}

export default Tooltip;

// src/lib/components/base/Tooltip.svelte
<script lang="ts">
	import clsx from 'clsx';
	import { ariaBool } from '$utils/aria';

	export let id = null;
	export let visible = false;

	let __class = '';
	export { __class as class };
</script>

<div
	{id}
	class={clsx('transition-opacity mt-1 z-50', !visible && 'opacity-0 invisible', __class)}
	role="tooltip"
	aria-hidden={ariaBool(!visible)}
>
	<span
		class="flex items-center justify-center rounded-sm bg-gray-50 py-1.5 px-2 text-sm font-medium tracking-wider shadow-sm dark:border-2"
	>
		<slot />
	</span>
</div>
